title: ""
description: ""
baseurl: ""
url: ""

exclude:
  - demo/
  - hacked-jekyll.gemspec
  - LICENSE
  - README.md
  - screenshot.png

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  style: compressed
  sourcemap: never
