title: Hacked Jekyll
description: Jekyll microtheme that looks like JSON
baseurl: /hacked-jekyll
url: https://piazzai.github.io

theme: hacked-jekyll

lowercase: true
show_quotes: true
show_commas: true
target: _self

exclude:
  - LICENSE
  - README.md

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  sourcemap: never
  