title: Lorem Ipsum
description: Lorem Ipsum is simply dummy text of the printing and typesetting industry.
baseurl: /hacked-jekyll
url: https://0xxertz.github.io/

theme: hacked-jekyll

exclude:
  - LICENSE
  - README.md
  - vendor/

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  sourcemap: never
  
